# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c789af9335ecdae2dec3949ca61eb935"
application_url = "https://biol-chris-guest-kijiji.trycloudflare.com"
embedded = true
name = "ticket-booking-system"
handle = "ticket-booking-system"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://biol-chris-guest-kijiji.trycloudflare.com/auth/callback",
  "https://biol-chris-guest-kijiji.trycloudflare.com/auth/shopify/callback",
  "https://biol-chris-guest-kijiji.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "naeems-ticket.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
